jobs:
  lint:
    runs-on: ubuntu-latest
    environment: release
    name: Lint
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
    timeout-minutes: 10
  build:
    runs-on: ubuntu-latest
    environment: release
    name: Build
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run build
    timeout-minutes: 10
  test:
    runs-on: ubuntu-latest
    environment: release
    name: Test
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npx playwright install
      - run: npm run test
    timeout-minutes: 10
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
